services:

  web1:
    image: nginx:alpine
    container_name: web1
    volumes:
      - ./web1:/usr/share/nginx/html
    ports:
      - "8081:80"

  web2:
    image: nginx:alpine
    container_name: web2
    volumes:
      - ./web2:/usr/share/nginx/html
    ports:
      - "8082:80"

  db:
    image: mysql:8
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: root1234
      MYSQL_DATABASE: projet_b2
      MYSQL_USER: user_b2
      MYSQL_PASSWORD: pass1234
    ports:
      - "3306:3306"